//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.ESI.SUEP.Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUEPEntities : DbContext
    {
        public SUEPEntities()
            : base("name=SUEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TbSuep_User> TbSuep_User { get; set; }
        public virtual DbSet<TbSuep_User_Type> TbSuep_User_Type { get; set; }
        public virtual DbSet<TbSuep_Agenda> TbSuep_Agenda { get; set; }
    }
}
