//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.ESI.SUEP.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbSuep_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbSuep_User()
        {
            this.TbSuep_Agenda = new HashSet<TbSuep_Agenda>();
            this.TbSuep_Agenda1 = new HashSet<TbSuep_Agenda>();
        }
    
        public long Id { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public int Id_User_Type { get; set; }
        public string Name { get; set; }
        public string CPF { get; set; }
        public bool FlActive { get; set; }
        public Nullable<decimal> HourPrice { get; set; }
    
        public virtual TbSuep_User_Type TbSuep_User_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbSuep_Agenda> TbSuep_Agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbSuep_Agenda> TbSuep_Agenda1 { get; set; }
    }
}
