//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.ESI.SUEP.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbSuep_Agenda
    {
        public int Id { get; set; }
        public System.DateTime Dt_Begin { get; set; }
        public System.DateTime Dt_End { get; set; }
        public long Id_User_Doctor { get; set; }
        public long Id_User_Pacient { get; set; }
    
        public virtual TbSuep_User TbSuep_User { get; set; }
        public virtual TbSuep_User TbSuep_User1 { get; set; }
    }
}
