//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.ESI.SUEP.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbSuep_Note
    {
        public int Id { get; set; }
        public int Id_Agenda { get; set; }
        public string Note { get; set; }
    
        public virtual TbSuep_Agenda TbSuep_Agenda { get; set; }
    }
}
